/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Color;
import java.awt.Point;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.Autos;
import modelo.MovAuto1;
import modelo.MovAuto2;
import modelo.MovAuto3;

/**
 *
 * @author Marvin
 */
public class Juego extends javax.swing.JFrame {

    /**
     * Creates new form Juego
     */
    public static Point caball1=new Point(0, 120);
    public static Point caball2=new Point(0, 240);
    public static Point caball3=new Point(0, 350);
    public String Jganadores="";
    public static int puesto=0;
    public static boolean bandera=true;
    public static Juego fram;
    public static MovAuto1 caba1= new MovAuto1();
    public static MovAuto2 caba2= new MovAuto2();
    public static MovAuto3 caba3= new MovAuto3();
    public static Autos iniciar= new Autos();
    public Juego() throws InterruptedException{
        initComponents();
        this.setSize(950, 470);
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Carreras de Autos");
        this.getContentPane().setBackground(Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        Auto1 = new javax.swing.JLabel();
        Auto2 = new javax.swing.JLabel();
        Auto3 = new javax.swing.JLabel();
        Salida = new javax.swing.JLabel();
        Meta = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();
        Resultados = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        RGanadores = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 0, 79, 25);

        Auto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/auto1.gif"))); // NOI18N
        getContentPane().add(Auto1);
        Auto1.setBounds(-4, 120, 100, 54);

        Auto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/auto2.gif"))); // NOI18N
        getContentPane().add(Auto2);
        Auto2.setBounds(1, 240, 100, 60);

        Auto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/auto3.gif"))); // NOI18N
        getContentPane().add(Auto3);
        Auto3.setBounds(10, 360, 90, 50);

        Salida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salida.png"))); // NOI18N
        getContentPane().add(Salida);
        Salida.setBounds(100, 100, 20, 340);

        Meta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/meta.png"))); // NOI18N
        getContentPane().add(Meta);
        Meta.setBounds(660, 100, 43, 330);

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(Fondo);
        Fondo.setBounds(0, 0, 756, 440);

        Resultados.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Resultados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fp.png"))); // NOI18N
        getContentPane().add(Resultados);
        Resultados.setBounds(760, 0, 190, 60);

        RGanadores.setBackground(new java.awt.Color(0, 0, 0));
        RGanadores.setBorder(new javax.swing.border.MatteBorder(null));
        RGanadores.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        RGanadores.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(RGanadores);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(760, 80, 190, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(!caba1.isAlive() && !caba2.isAlive() && !caba3.isAlive()){            
            RGanadores.setText("");
            puesto=0;
            Auto1.setLocation(caball1);
            Auto2.setLocation(caball2);
            Auto3.setLocation(caball3);

            caba1= new MovAuto1();
            caba2= new MovAuto2();
            caba3= new MovAuto3();
            caba1.setName("caballo1");
            caba2.setName("caballo2");
            caba3.setName("caballo3");
     
            caba1.start();
            caba2.start();
            caba3.start();
        }
        if (bandera) iniciar.start();
        bandera=false;
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.lang.InterruptedException
     */
    public static void main(String args[]) throws InterruptedException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        fram=new Juego();
        fram.setVisible(true);
        
        caba1.join();
        caba2.join();
        caba3.join();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Juego().setVisible(true);
            } catch (InterruptedException ex) {
                Logger.getLogger(Juego.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Auto1;
    public static javax.swing.JLabel Auto2;
    public static javax.swing.JLabel Auto3;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Meta;
    public static javax.swing.JTextPane RGanadores;
    public static javax.swing.JLabel Resultados;
    private javax.swing.JLabel Salida;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
