/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Color;
import java.awt.Point;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.Autos;
import modelo.MovAuto1;
import modelo.MovAuto2;
import modelo.MovAuto3;

/**
 *
 * @author Marvin
 */
public class Juego extends javax.swing.JFrame {

    /**
     * Creates new form Juego
     */
    public static Point posicionA1=new Point(0, 120);
    public static Point posicionA2=new Point(0, 240);
    public static Point posicionA3=new Point(0, 350);
//    public String Jganadores="";
    public static int puesto=0;
    public static boolean bandera=true;
//    public static Juego fram;
    public static MovAuto1 MovA1= new MovAuto1();
    public static MovAuto2 MovA2= new MovAuto2();
    public static MovAuto3 MovA3= new MovAuto3();
    public static Autos iniciar= new Autos();
    public Juego() throws InterruptedException{
        initComponents();
        this.setSize(990, 490);
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Carreras de Autos");
        this.getContentPane().setBackground(Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        INICIAR = new javax.swing.JButton();
        Auto1 = new javax.swing.JLabel();
        Auto2 = new javax.swing.JLabel();
        Auto3 = new javax.swing.JLabel();
        Salida = new javax.swing.JLabel();
        Meta = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();
        Resultados = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Pizarra = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        INICIAR.setBackground(new java.awt.Color(0, 0, 0));
        INICIAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/INICIAR1.png"))); // NOI18N
        INICIAR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        INICIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INICIARActionPerformed(evt);
            }
        });
        getContentPane().add(INICIAR);
        INICIAR.setBounds(0, 50, 120, 50);

        Auto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/auto1.gif"))); // NOI18N
        Auto1.setToolTipText("Auto Rojo");
        getContentPane().add(Auto1);
        Auto1.setBounds(-4, 120, 100, 54);

        Auto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/auto2.gif"))); // NOI18N
        Auto2.setToolTipText("Auto Azul");
        getContentPane().add(Auto2);
        Auto2.setBounds(1, 240, 100, 60);

        Auto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/auto3.gif"))); // NOI18N
        Auto3.setToolTipText("Auto Gris");
        getContentPane().add(Auto3);
        Auto3.setBounds(10, 360, 90, 50);

        Salida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salida2.png"))); // NOI18N
        getContentPane().add(Salida);
        Salida.setBounds(100, 100, 20, 340);

        Meta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/meta.png"))); // NOI18N
        getContentPane().add(Meta);
        Meta.setBounds(660, 100, 43, 330);

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(Fondo);
        Fondo.setBounds(0, 0, 756, 440);

        Resultados.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Resultados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fp.png"))); // NOI18N
        getContentPane().add(Resultados);
        Resultados.setBounds(770, 20, 190, 60);

        Pizarra.setEditable(false);
        Pizarra.setBackground(new java.awt.Color(0, 0, 0));
        Pizarra.setColumns(20);
        Pizarra.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        Pizarra.setForeground(new java.awt.Color(255, 255, 255));
        Pizarra.setRows(5);
        Pizarra.setTabSize(6);
        Pizarra.setToolTipText("Tabla Ganadores");
        jScrollPane1.setViewportView(Pizarra);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(760, 90, 210, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void INICIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INICIARActionPerformed
        if(!MovA1.isAlive() && !MovA2.isAlive() && !MovA3.isAlive()){            
            Pizarra.setText("");//limpia la tabla de ganadores
            puesto=0;
            //////
            Auto1.setLocation(posicionA1);
            MovA1= new MovAuto1();
            MovA1.setName("Auto Rojo");
            //////
            Auto2.setLocation(posicionA2);
            MovA2= new MovAuto2();
            MovA2.setName("Auto Azul");
            //////
            Auto3.setLocation(posicionA3);
            MovA3= new MovAuto3();
            MovA3.setName("Auto Gris");
            /////Iniciar los 3
            MovA1.start();
            MovA2.start();
            MovA3.start();
        }
        if (bandera) iniciar.start();
        bandera=false;
    }//GEN-LAST:event_INICIARActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.lang.InterruptedException
     */
    public static void main(String args[]) throws InterruptedException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Juego().setVisible(true);
            } catch (InterruptedException ex) {
                Logger.getLogger(Juego.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Auto1;
    public static javax.swing.JLabel Auto2;
    public static javax.swing.JLabel Auto3;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton INICIAR;
    private javax.swing.JLabel Meta;
    public static javax.swing.JTextArea Pizarra;
    public static javax.swing.JLabel Resultados;
    private javax.swing.JLabel Salida;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
